spring:
  datasource:
    url: jdbc:mysql://localhost:3306/index_test?serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: 1225
    driver-class-name: com.mysql.cj.jdbc.Driver
